add crud operation for category -> tag
AndriiHolovianko/exadel_sandbox pull request #58
Opened 2021-07-03 18:32 UTC by serghalak

add create category with tags, update category with tags and delete category with tags

2021-07-03 19:31 UTC, Helen1711 requested changes

2021-07-03 19:31 UTC, Helen1711 commented on sandbox-service/src/main/java/com/exadel/sandbox/service/impl/TagServiceImpl.java
> +
Does these changes belong to the scope of your task?
I am asking because they are part of my task  (tag api).
Was this agreed with me?

2021-07-04 09:40 UTC, RosKokos approved these changes

2021-07-04 13:58 UTC, KrasuliaV approved these changes

2021-07-05 05:00 UTC, RosKokos approved these changes

2021-07-05 10:26 UTC, merged